### ISSUE TITLE
网页终端无法打开，页面提示无法访问此网站

### ISSUE THREAD

**Issue by Aurora209** [msechen/jdv5#2]
网页终端无法打开，页面提示无法访问此网站

`======================== 5. 启动网页终端 ========================
cp: cannot stat '/jd/panel/ttyd/ttyd.armv7l': No such file or directory`

**Comment by 4499dsq** [comment]
一样的问题，重装了几次，没找到哪的问题

**Comment by msechen** [comment]
默认关闭网页中断，要打开将ttyd设置成true
